# Generated by Django 6.0.6 on 2026-07-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('raw_query', models.TextField()),
                ('rewritten_query', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('vector_chunks', models.JSONField(default=list)),
                ('bm_25_chunks', models.JSONField(default=list)),
                ('fused_chunks', models.JSONField(default=list)),
                ('cited_chunks', models.JSONField(default=list)),
                ('raw_answer', models.TextField()),
                ('parsed_answer', models.JSONField()),
                ('feedback', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orchestrator_agent.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='orchestrato_session_d9e32f_idx')],
            },
        ),
    ]
