# Generated by Django 6.0.6 on 2026-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_qa_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
