# Generated by Django 6.0.6 on 2026-07-01 10:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_agent', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('chunk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('freshdesk', 'Freshdesk'), ('freshdesk_ticket', 'Freshdesk Ticket'), ('notion_page', 'Notion Page'), ('loom_video', 'Loom Video')], max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('source_url', models.TextField(blank=True, default='')),
                ('position', models.IntegerField()),
                ('content', models.TextField()),
                ('searchable_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model_id', models.CharField(max_length=255)),
                ('content_tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('searchable_text', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('token_count', models.IntegerField(default=0)),
                ('chunk_strategy', models.CharField(choices=[('heading_aware', 'Heading Aware'), ('recursive_fallback', 'Recursive Fallback')], max_length=50)),
                ('context_prefix', models.TextField(blank=True, null=True)),
                ('chunk_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=None)),
                ('deleted_at', models.DateTimeField()),
                ('doc_id', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, to='process_agent.document')),
            ],
            options={
                'db_table': 'chunks',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunks_embedding_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['content_tsv'], name='chunks_content_tsv_gin')],
                'constraints': [models.UniqueConstraint(fields=('doc_id', 'position'), name='unique_chunk_position')],
            },
        ),
    ]
